'use strict';
const DATA=JSON.parse(document.getElementById('datos-eba').textContent);
const $=id=>document.getElementById(id), val=id=>Number($(id).value), txt=id=>$(id).value;
const fmt=(v,d=2)=>Number(v).toLocaleString('es-CL',{minimumFractionDigits:d,maximumFractionDigits:d});
const mean=x=>x.reduce((a,b)=>a+b,0)/x.length;
const sd=x=>Math.sqrt(x.reduce((a,b)=>a+(b-mean(x))**2,0)/(x.length-1));
function filter(canal='Todos',campana='Todas'){return DATA.pedidos.filter(r=>(canal==='Todos'||r.canal===canal)&&(campana==='Todas'||r.campana===campana));}
function kpis(canal='Todos',campana='Todas'){const d=filter(canal,campana);return {n:d.length,ticket:mean(d.map(x=>x.ticket_mil)),tiempo:mean(d.map(x=>x.tiempo_min)),resueltos:100*mean(d.map(x=>x.resuelto))};}
function bayes(p,s,e){const tp=p*s,fp=(1-p)*(1-e);return {tp,fp,posterior:tp+fp?tp/(tp+fp):null};}
function muestra(e,r){const n0=1.959963984540054**2*.25/e**2,n=Math.ceil(n0/(1+(n0-1)/5000));return {n,invitaciones:Math.ceil(n/r)};}
function binomial(n,p,k){if(k>n)return 0;if(k<=0)return 1;let term=(1-p)**n,total=0;for(let i=0;i<=n;i++){if(i>=k)total+=term;term*=((n-i)/(i+1))*p/(1-p);}return Math.min(1,total);}
function intervalo(n,c){const x=DATA.pedidos.slice(0,n).map(r=>r.tiempo_min),m=mean(x),se=sd(x)/Math.sqrt(n),d=DATA.tcrit[String(n)][String(c)]*se;return {n,media:m,se,li:m-d,ls:m+d};}
function correlacion(c){const d=filter(c),x=d.map(r=>r.ticket_mil),y=d.map(r=>r.tiempo_min),mx=mean(x),my=mean(y);return x.reduce((a,v,i)=>a+(v-mx)*(y[i]-my),0)/Math.sqrt(x.reduce((a,v)=>a+(v-mx)**2,0)*y.reduce((a,v)=>a+(v-my)**2,0));}
function ses(alpha){const y=DATA.serie.slice(0,36),niveles=[y[0]];for(let i=1;i<y.length;i++)niveles.push(alpha*y[i]+(1-alpha)*niveles.at(-1));return niveles;}
function beneficio(costo,valor){const r=DATA.welch;return {medio:-r.diferencia*valor-costo,li:-r.ls*valor-costo,ls:-r.li*valor-costo};}
function cards(k){return `<div class="kpis"><div class="kpi"><strong>${k.n}</strong><span>Pedidos</span></div><div class="kpi"><strong>${fmt(k.tiempo)}</strong><span>Tiempo medio · min</span></div><div class="kpi"><strong>${fmt(k.ticket)}</strong><span>Ticket medio · miles UM</span></div><div class="kpi"><strong>${fmt(k.resueltos,1)}%</strong><span>Resueltos / pedidos</span></div></div>`;}
function plot(id,series,scatter=false){const canvas=$(id),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const xs=series.flatMap(s=>s.x),ys=series.flatMap(s=>s.y);const xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);const X=x=>48+(x-xmin)/(xmax-xmin||1)*(w-70),Y=y=>h-40-(y-ymin)/(ymax-ymin||1)*(h-65);ctx.strokeStyle='#9db6bf';ctx.beginPath();ctx.moveTo(48,15);ctx.lineTo(48,h-40);ctx.lineTo(w-20,h-40);ctx.stroke();ctx.fillStyle='#254b59';ctx.font='13px system-ui';ctx.fillText(fmt(ymax,0),5,25);ctx.fillText(fmt(ymin,0),5,h-38);ctx.fillText(fmt(xmin,0),45,h-20);ctx.fillText(fmt(xmax,0),w-55,h-20);for(const s of series){ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.beginPath();s.x.forEach((x,i)=>{if(scatter){ctx.moveTo(X(x)+2,Y(s.y[i]));ctx.arc(X(x),Y(s.y[i]),2,0,2*Math.PI);}else if(i===0)ctx.moveTo(X(x),Y(s.y[i]));else ctx.lineTo(X(x),Y(s.y[i]));});if(scatter)ctx.fill();else ctx.stroke();}}
function render(){document.querySelectorAll('input[type=range]').forEach(x=>$(x.id+'-v').textContent=x.value);
const metodos={describir:'Frecuencias, centro, dispersión y gráficos. Definir primero la unidad.',medias:txt('diseno')==='pareado'?'t de diferencias pareadas; la unidad es la persona medida dos veces.':'Welch para dos grupos independientes; efecto, IC y supuesto de independencia.',proporcion:'Proporción e IC Wilson bajo modelo binomial; informar numerador y denominador.',relacion:'Dispersión, correlación y regresión; asociación no prueba causalidad.',futuro:'Referencia temporal, suavizamiento o ARIMA, con evaluación por origen temporal.'};$('metodo-resultado').textContent=metodos[txt('objetivo')];
$('resumen-resultado').innerHTML=cards(kpis(txt('resumen-canal')));
const m=muestra(val('margen'),val('respuesta'));$('muestra-resultado').textContent=`N=5.000, confianza 95%, p=.5: ${m.n} respuestas completas; ${m.invitaciones} invitaciones. Aproximación bajo muestreo aleatorio simple; no corrige sesgo de no respuesta.`;
const ec=txt('evento-campana'),g=filter('Todos',ec),k=g.filter(r=>r.resuelto).length;$('eventos-resultado').textContent=`P(resuelto | ${ec}) = ${k}/${g.length} = ${fmt(k/g.length,3)}. P(resuelto ∩ ${ec}) = ${k}/600 = ${fmt(k/600,3)}. Denominadores diferentes.`;
const b=bayes(val('prevalencia'),val('sensibilidad'),val('especificidad'));$('bayes-resultado').textContent=`Por 10.000 casos: ${fmt(b.tp*10000,1)} alertas verdaderas y ${fmt(b.fp*10000,1)} falsas. P(riesgo | alerta) = ${fmt(100*b.posterior,2)}%. Conteos esperados.`;
$('binomial-resultado').textContent=`P(X ≥ ${val('bin-k')}) = ${fmt(binomial(val('bin-n'),val('bin-p'),val('bin-k')),6)}; E[X]=${fmt(val('bin-n')*val('bin-p'))}. Meta superior a n tiene probabilidad cero.`;
const ic=intervalo(val('ic-n'),val('ic-nivel'));$('intervalo-resultado').textContent=`Media ${fmt(ic.media)} min; SE ${fmt(ic.se)}; IC ${fmt(100*val('ic-nivel'),0)}% [${fmt(ic.li)}, ${fmt(ic.ls)}]. No es un intervalo para pedidos individuales.`;
const d=filter(txt('relacion-canal'));$('relacion-resultado').textContent=`n=${d.length}; Pearson r=${fmt(correlacion(txt('relacion-canal')),3)}. Eje horizontal: ticket (miles UM); vertical: tiempo (min).`;plot('dispersion',[{x:d.map(x=>x.ticket_mil),y:d.map(x=>x.tiempo_min),color:'#087f8c80'}],true);
const beneficioActual=beneficio(val('costo'),val('valor'));$('decision-resultado').textContent=`B frente a A: ${fmt(beneficioActual.medio,3)} UM/pedido; IC transformado [${fmt(beneficioActual.li,3)}, ${fmt(beneficioActual.ls,3)}]. Costos fijos supuestos; no es incertidumbre total del negocio.`;
const a=DATA.anova[txt('anova-canal')];$('anova-resultado').textContent=`ANOVA clásico F=${fmt(a.F,3)}, p=${a.p.toExponential(3)}; Welch F=${fmt(a.F_Welch,3)}, p=${a.p_Welch.toExponential(3)}; eta²=${fmt(a.eta2,3)}. Cálculo SciPy precalculado para cada filtro.`;
const smooth=ses(val('alpha'));$('suavizamiento-resultado').textContent=`Nivel al mes 36: ${fmt(smooth.at(-1))} unidades. Solo datos de desarrollo: no se selecciona alfa mirando la prueba. Eje horizontal: mes 1–36; vertical: unidades. Azul: demanda; naranja: nivel.`;plot('serie',[{x:smooth.map((_,i)=>i+1),y:DATA.serie.slice(0,36),color:'#087f8c'},{x:smooth.map((_,i)=>i+1),y:smooth,color:'#b66a0a'}]);
$('dashboard-resultado').innerHTML=cards(kpis(txt('dash-canal'),txt('dash-campana')));}
document.querySelectorAll('.controles input,.controles select').forEach(x=>x.addEventListener('input',render));
document.querySelectorAll('[data-quiz]').forEach(b=>b.addEventListener('click',()=>{const fs=b.closest('fieldset'),x=fs.querySelector('input:checked');fs.querySelector('p').textContent=x?(x.value==='1'?'Correcto. ':'Revisa. ')+b.dataset.explicacion:'Selecciona una respuesta.';}));
$('buscar').addEventListener('input',()=>{const q=$('buscar').value.trim().toLocaleLowerCase('es'),secs=[...document.querySelectorAll('section.level1')];secs.forEach(s=>s.hidden=!s.textContent.toLocaleLowerCase('es').includes(q));$('sin-resultados').hidden=secs.some(s=>!s.hidden);});
document.querySelectorAll('aside nav a').forEach(a=>a.addEventListener('click',()=>{$('buscar').value='';document.querySelectorAll('section.level1').forEach(s=>s.hidden=false);$('sin-resultados').hidden=true;}));
window.EBA={kpis,bayes,muestra,binomial,intervalo,correlacion,ses,beneficio,render};render();
