"""Problemas de transferencia y pautas separadas; no reemplazan evaluación institucional."""
# Enunciado nuevo, pauta docente, error frecuente y pregunta de discusión.
PRACTICAS = {
 'FBA': [
  ('Un piloto contactará 2.000 clientes. Se supone que el abandono baja de 10% a 8%, cada retención vale 120 UM y cada contacto cuesta 2 UM. Formula decisión, unidad, horizonte y beneficio. ¿Qué dato falta para comprobar el efecto con el archivo de ventas?',
   'Retenciones incrementales esperadas: 2000×(.10−.08)=40; beneficio 40×120−2000×2=800 UM. Es un escenario, no efecto estimado. El CSV de ventas no identifica clientes ni asignación a tratamiento/control: no permite comprobar retención.',
   'Confundir ventas con clientes o una reducción absoluta de 2 puntos con 2% relativo.',
   '¿Qué resultado del piloto justificaría detener la campaña?'),
  ('Dos canales tienen 30 y 90 transacciones e ingresos de 9.000 y 18.000 UM. Calcula el ticket general, diseña un gráfico con su denominador y explica una comparación engañosa. Después construye un gráfico propio del CSV sin copiar el tablero.',
   'Tickets 300 y 200; ticket general 27000/120=225 UM. El promedio simple 250 responde a canales con igual peso, no a una transacción elegida del total. El gráfico debe identificar período, cantidad de transacciones y unidad.',
   'Promediar promedios sin pesos o interpretar asociación como efecto del canal.',
   '¿Cómo cambia la interpretación si el objetivo es comparar canales con igual peso?'),
  ('Trabaja en una copia del libro FBA_herramientas.xlsx. Filtra un canal y trimestre, calcula ingresos y ticket en Excel y pandas. Duplica una clave del catálogo y explica qué control debe detener una unión; entrega una recomendación de una página.',
   'Las filas incluidas deben coincidir antes de comparar resultados. Ticket = suma de Monto / número de ID_Venta únicos. La dimensión repetida viola many_to_one; resolver el catálogo antes de unir, no compensar después dividiendo totales.',
   'Comparar universos distintos o sumar porcentajes de grupos.',
   '¿Qué control distinguiría una devolución legítima de una copia duplicada?'),
  ('En 10.000 casos, prevalencia 1%, sensibilidad 90% y especificidad 95%: predice el valor de una alerta antes de calcular. Repite con prevalencia 10% y justifica el cambio. Explica qué reduce cuadruplicar las simulaciones.',
   'Con 1%: VP=90 y FP=495; posterior=90/585≈15,38%. Con 10%: VP=900 y FP=450; posterior≈66,67%. Cuadruplicar N reduce aproximadamente a la mitad el error Monte Carlo, no el sesgo ni el riesgo subyacente.',
   'Confundir sensibilidad con probabilidad de condición dada alerta.',
   '¿En qué situación no se cumpliría independencia entre simulaciones?'),
  ('Diseña cuatro tarjetas: datos para ajuste, selección, regla de decisión y prueba. Cambia el costo FN de 5 a 10 manteniendo FP=1 y explica qué puede cambiar antes de abrir la prueba. Formula un uso de clusters que deba validarse después.',
   'La regla teórica pasa de 1/6 a 1/11 si hay calibración y la estructura de costos es esa. Umbral/selección se fijan fuera de prueba; no se elige el resultado más favorable de prueba. Los clusters describen perfiles; su uso comercial requiere evaluación posterior.',
   'Modificar el modelo tras mirar prueba o ordenar personas por número de cluster.',
   '¿Cómo demostrarías valor incremental sobre contactar a todos?')],
 'EBA': [
  ('Una muestra toma el mismo número de pedidos Web y Tienda. Sus medias son 10 y 20 minutos, pero la población contiene 70% Web y 30% Tienda. Estima la media poblacional y contrasta con el promedio sin ponderar. Redacta la ficha de muestreo.',
   'Media ponderada=.7×10+.3×20=13 min; promedio sin pesos=15. Los pesos provienen del marco, no de la cuota muestral. Distinguir objetivo finito de pedidos futuros; el diseño y la cobertura son parte del contrato.',
   'Usar cuotas muestrales como si fueran pesos poblacionales.',
   '¿Qué ocurriría si no se conociera la proporción de Tienda?'),
  ('Construye una tabla 2×2 para 10.000 alertas potenciales con prevalencia 3%, sensibilidad 85% y especificidad 94%. Calcula P(riesgo|alerta) sin llamar al helper. Elige una distribución para llegadas y justifica un supuesto que podría fallar.',
   'VP=255, FN=45, FP=582, VN=9118; posterior=255/837≈30,47%. Poisson exige supuestos sobre tasa e independencia; ráfagas o congestión pueden invalidarlos. Los conteos son esperados.',
   'Aplicar especificidad a todos los casos en vez de a los negativos.',
   '¿Por qué una alerta no equivale a una clasificación confirmada?'),
  ('Con n=25 pedidos independientes, media 12 minutos y SD=5, construye el IC t del 95% paso a paso. Indica qué parámetro cubre. Compara con n=100 manteniendo media y SD.',
   'SE=5/√25=1; t24≈2,064; IC≈[9,936;14,064]. Para n=100, SE=.5 y t99≈1,984: [11,008;12,992]. Se estima la media de la población objetivo, no el rango del 95% de los pedidos.',
   'Sustituir SD por SE o asignar probabilidad posterior al parámetro fijo.',
   '¿Se conserva la validez si los 25 pedidos pertenecen a una misma sucursal?'),
  ('Un modelo de tiempo incluye ticket, canal y campaña. El coeficiente de ticket es .08 min por mil UM. Interpreta un incremento de 20 mil UM, distingue IC del coeficiente e intervalo de un pedido y propone un diagnóstico de residuos.',
   'Cambio condicional esperado 1,6 min manteniendo las otras variables fijas y dentro del rango. No es una intervención causal. El IC cuantifica incertidumbre del parámetro; el intervalo predictivo incluye variación individual. Revisar residuos frente a ajuste, tiempo y grupos.',
   'Interpretar HC3 como solución para especificación incorrecta o dependencia ignorada.',
   '¿Qué información necesitarías para defender un efecto causal del ticket?'),
  ('B−A en tiempo tiene IC95% [−6,−2] min y estimación −4. B cuesta 5 UM adicionales por pedido y ahorrar un minuto vale 1 UM. Decide si significación estadística basta para recomendar B y elige la prueba para datos independientes o pareados.',
   'Beneficio estimado 4−5=−1 UM; al transformar el intervalo: [2−5,6−5]=[−3,1]. Mejora de tiempo no implica rentabilidad. Welch para grupos independientes; contraste de diferencias si las mismas unidades se miden dos veces, con sus supuestos.',
   'Equiparar p pequeño con conveniencia económica o parear observaciones arbitrariamente.',
   '¿Qué cambia si se comparan las tres campañas y luego se elige la mejor?'),
  ('Para reales [120,150,180], una referencia predice [110,160,170] y otro método [125,140,190]. Calcula MAE. Dibuja entrenamiento, selección y prueba por fechas para un horizonte de tres meses; explica cuándo se conoce cada error.',
   'MAE referencia=10; segundo=(5+10+10)/3≈8,33. La comparación requiere el mismo horizonte y orígenes. Cada error solo está disponible al observar su fecha objetivo; no se mezcla prueba en la selección.',
   'Comparar horizontes distintos o calibrar con resultados posteriores a la emisión.',
   '¿Es válido tratar errores de orígenes solapados como independientes?'),
  ('Filtra Tienda en ComercioSur y concilia cantidad, tiempo medio y resolución en Python, Excel y la consulta Power Query entregada. Diseña una tarea de usuario que evalúe comprensión del tablero manteniendo iguales los datos.',
   'Primero conciliar universo y tipos; cantidades suman, medias/tasas se recalculan desde numeradores y denominadores. Registrar valores y filtros en cada herramienta. Un experimento de comprensión puede medir aciertos/tiempo con asignación y tareas iguales; no demuestra por sí solo impacto comercial.',
   'Atribuir cambios comerciales al diseño sin contrafactual.',
   '¿Cuál es la diferencia entre una fórmula escrita y una fórmula recalculada por Excel?'),
  ('Una campaña reduce tiempo: IC de B−A [−5,−1] min. Para resolución el IC de diferencia es [−.06,.02]; el margen de no inferioridad predefinido es −.03. Redacta un memo de 100 palabras con decisión, incertidumbre y siguiente evidencia.',
   'Hay reducción de tiempo bajo el diseño, pero no se acredita no inferioridad de resolución porque el límite inferior −.06 cruza −.03. No rechazo de igualdad no demuestra equivalencia. Proponer decisión condicionada a costos/guardarraíl y un diseño con precisión suficiente.',
   'Convertir un resultado no significativo en ausencia de deterioro.',
   '¿Qué información del diseño debe acompañar ambos intervalos?')],
 'MPN': [
  ('Se quiere predecir abandono al inicio de un trimestre. Hay reclamos del trimestre anterior, fecha de cancelación y descuento ofrecido después de cancelar. Define Y, unidad, instante y baseline; justifica variables admisibles y distingue el ejemplo de red fija de entrenar una red.',
   'Reclamos previos pueden ser admisibles; cancelación y descuento posterior son fuga. Y necesita horizonte de abandono explícito. Baseline de prevalencia aprendido en ajuste; comparar AP/costo según decisión. La red fija ilustra propagación, no aprendizaje de pesos.',
   'Usar disponibilidad en la base como equivalente a disponibilidad al decidir.',
   '¿Cómo probarías que el pipeline operativo respeta el instante de corte?'),
  ('Los ingresos altos presentan más ausencias. Propón dos tratamientos, explica sus límites y diseña la validación. La tasa base es .28 y el criterio acordado AP≥2×base y AUC≥.70: informa cumplimiento con tus resultados, incluso si falla.',
   'Mediana e indicador de ausencia pueden ser comparadores; ninguno elimina por sí solo MNAR. Buscar otra fuente y documentar incertidumbre. Cada transformación se ajusta dentro del entrenamiento correspondiente. El umbral AP es .56; informar AP/AUC y no rebajar el criterio para aprobar.',
   'Imputar con toda la tabla o declarar que un buen AUC elimina sesgo de selección.',
   '¿Qué harías si el modelo no alcanza el criterio antes de la prueba?'),
  ('Con modelo congelado que predice 20 y residuos absolutos de calibración [1,2,3,4,5,6,7,8,9], calcula el intervalo conformal 80%. Identifica qué conjunto puede elegir alpha y qué cambia si reajustas después con calibración.',
   'k=ceil(10×.8)=8; q=8; intervalo [12,28]. Alpha se selecciona con CV interna de ajuste, reestimando el escalador por fold. Reajustar tras calibrar invalida la justificación de ese cuantil; hay que reservar/calibrar de nuevo con datos independientes.',
   'Confundir conjunto de selección con calibración o prometer cobertura por segmento.',
   '¿Qué ocurre si se pide un nivel que el tamaño de calibración no permite?'),
  ('Probabilidad base .25 y odds ratio 1.5 por una unidad: calcula la nueva probabilidad. Luego compara dos modelos en los mismos clientes de validación y explica qué incertidumbre de la diferencia debes examinar antes de prometer superioridad.',
   'Chances base=1/3; nuevas=.5; probabilidad=1/3. Remuestrear pares de clientes preserva el emparejamiento de predicciones para una diferencia condicional; para incluir selección/entrenamiento hay que repetir ese proceso. No elegir el modelo con la prueba.',
   'Multiplicar directamente la probabilidad por el odds ratio o usar intervalos marginales como prueba de diferencia.',
   '¿Un AUC mayor siempre produce una campaña más rentable?'),
  ('Con TP=30, FN=10, FP=20, TN=140 y costos FN=8, FP=2, calcula precisión, recall y costo medio. Fija una política antes de evaluar. Explica qué captura el bootstrap sobre predicciones OOF ya calculadas.',
   'Precisión=.60; recall=.75; costo=(10×8+20×2)/200=.60 UM/caso; t*=.2 si hay calibración y ese modelo de costos. Bootstrap de pares OOF fijos es condicional a esas predicciones; no reproduce toda la incertidumbre de selección/entrenamiento.',
   'Optimizar el umbral en prueba o llamar a un intervalo condicional garantía operacional.',
   '¿Cuántos eventos positivos sostienen tu estimación de recall?'),
  ('Una variable binaria pasa de proporciones [.90,.10] a [.60,.40]. Calcula PSI conservando dos categorías. Propón un tratamiento para un faltante y una categoría nueva y redacta una alerta sin afirmar caída del AUC.',
   'PSI=(−.3)ln(.6/.9)+.3ln(.4/.1)≈.5375. Las categorías nuevas y faltantes deben tener conteos explícitos; documentar regularización de ceros. Investigar registro/población/proceso y esperar etiquetas para medir desempeño.',
   'Colapsar una variable discreta en un único intervalo o usar PSI como prueba causal.',
   '¿Por qué el PSI numérico depende del esquema de tramos y de epsilon?'),
  ('Al emitir en abril solo se observan resultados hasta marzo. Un error de pronóstico tiene objetivo abril y otro marzo. Decide cuáles pueden calibrar el intervalo y escribe una condición con fechas. Explica el límite de usar el mismo backtest para escoger y evaluar el método.',
   'Solo el error con objetivo marzo está disponible. Condición fecha_objetivo < fecha_emision. Un origen temprano no basta si su horizonte termina después del corte. Si se selecciona con el backtest, se requiere otra ventana para evaluar la selección.',
   'Partir orígenes por la mitad sin comprobar cuándo se conoce la respuesta.',
   '¿Cómo incorporarías retrasos en la llegada de etiquetas?')],
 'AED': [
  ('Hay 100 clientes maduros: 72 activos, 18 abandonos y 10 estados desconocidos; además 40 inmaduros. Calcula retención observada y límites por faltantes. Documenta una actualización previa al ingreso sin inventar fechas.',
   'Retención observada=72/90=.80; límites entre 72/100=.72 y 82/100=.82. Los 40 inmaduros se informan aparte. Marcar la cronología, consultar significado y comparar sensibilidad; una fecha conflictiva no equivale a abandono.',
   'Usar 140 como denominador o imputar el estado faltante para mejorar el KPI.',
   '¿Qué diferencia hay entre cobertura de estado y representatividad?'),
  ('Obtén tres segmentos con otra semilla y compara la partición con la original. Explica por qué comparar etiquetas 0/1/2 directamente puede fallar. Diseña un uso y una comprobación comercial posteriores.',
   'Los números de cluster son arbitrarios; usar ARI sobre las mismas unidades permite comparar sin depender del nombre de la etiqueta. Estabilidad alta no demuestra utilidad. Para una campaña hace falta resultado, costo y evaluación de intervención.',
   'Confundir silhouette, estabilidad y rentabilidad como una única métrica.',
   '¿Puede haber grupos estables que no ayuden a decidir?'),
  ('Dos unidades generan ingresos 100 y 900 UM, con margen 10 y 50 UM. Calcula margen agregado. Diseña cuatro tarjetas con fórmula, período, denominador, responsable y acción; concilia una con la consulta Power Query entregada.',
   'Margen agregado=60/1000=6%; el promedio de 10% y 5,56% no responde al total. Tarjetas posibles: margen, reclamos por mil, entrega y cobertura de estado. Cada filtro debe conservar el grano y mostrar base.',
   'Mezclar ventas con marketing mensual mediante un join que multiplica filas.',
   '¿Cómo comprobarías que la medida cambia correctamente con un filtro?'),
  ('Reformula producción A/B para 130 horas y 100 unidades de material. Resuelve, verifica restricciones y compara contra una solución factible elegida a mano. Explica qué no demuestra el óptimo matemático.',
   'Intersección: A=160/3, B=70/3; contribución=8500/3 UM. Se verifica 2A+B=130 y A+2B=100, no negatividad y estado del solver. Factibilidad del modelo no demuestra exactitud de capacidades, divisibilidad o demanda.',
   'Sumar recursos con unidades diferentes o extrapolar un precio sombra sin reoptimizar.',
   '¿Qué restricción agregarías si A solo se produce en lotes de diez?'),
  ('Con probabilidad de demanda alta .6, calcula EV de expandir y pilotar, EVPI y el precio máximo defendible de información perfecta. Dibuja la secuencia señal→decisión→resultado y distingue EVPI de EVSI neto.',
   'Expandir=40, piloto=33 kUM. Con información perfecta: .4×15+.6×80=54; EVPI=14. Una señal imperfecta vale a lo sumo 14 bruto bajo este modelo; restar costo para obtener valor neto. Probabilidades posteriores se calculan por Bayes.',
   'Descontar dos veces inversión o interpretar EVPI como precio mínimo de cualquier estudio.',
   '¿Qué cambia si el decisor no acepta pérdidas en ningún estado?'),
  ('Duplica N manteniendo el modelo y después cambia shocks persistentes por anuales independientes. Predice qué cambia en SE y en la dispersión de VAN antes de ejecutar. Redacta una recomendación con límite de riesgo supuesto.',
   'Duplicar N reduce SE aproximadamente por 1/√2, sin cambiar la distribución objetivo. Cambiar dependencia temporal modifica la distribución del VAN; no es mejora numérica. Separar P(pérdida), percentiles, SE y supuestos; no ajustar el límite para aprobar.',
   'Presentar un IC Monte Carlo como incertidumbre total del proyecto.',
   '¿Qué parámetro económico necesitas estimar con datos externos antes de decidir?'),
  ('Un piloto cubre 10.000 pedidos: riesgo base .06, reducción relativa supuesta .15, costo evitado 25 UM y costo total 1.500 UM. Calcula beneficio y reducción absoluta. Prepara memo, alternativas y tres hitos de seguimiento.',
   'Evitados=90; beneficio=2250−1500=750 UM; reducción absoluta=.009, o .9 puntos porcentuales. Son supuestos, no impacto observado. Definir asignación, métrica primaria, guardarraíl, responsable, fecha y condición de parada.',
   'Comunicar 15 puntos porcentuales o presentar retorno supuesto como evidencia causal.',
   '¿Qué dato te haría preferir no implementar el piloto?'),
  ('Elige una estación: precio no lineal, cartera, cola o política secuencial. Para precio con costo 20 y q=120−2p, deriva el óptimo en [20,60]. Para otra estación, entrega hipótesis, referencia y sensibilidad, usando los prerrequisitos indicados.',
   'Precio: contribución=(p−20)(120−2p); derivada=160−4p; p*=40, q=40 y contribución=800. Segunda derivada −4 y dominio verifican óptimo. En cartera/colas/políticas exigir supuestos, restricciones y contraste independiente; un MDP conocido es planificación, no aprendizaje de transiciones.',
   'Interpretar un solver exitoso o una trayectoria UCB favorable como garantía de despliegue.',
   '¿Qué parte de la solución dejaría de ser válida si el modelo estuviera mal especificado?')]
}
