"""Contratos de aprendizaje compartidos por guías, manuales y notebooks.

Cada módulo declara un objetivo observable, preparación, ejemplo, práctica y evidencia.
Los tiempos son una estimación de trabajo guiado, ajustable al diagnóstico del grupo.
"""

CURSOS = {
 'FBA': {'carpeta':'01_Fundamentos_Business_Analytics','guia':'guia_maestra_ba.html','nombre':'Fundamentos de Business Analytics',
         'prerrequisito':'Porcentajes, lectura de tablas y operaciones básicas; Python se introduce con ejemplos.',
         'modulos':[
  ('c1','sec-negocio','Pregunta de negocio y datos','Formular una decisión con unidad de análisis, variable y regla de calidad.',
   'Distinguir una fila de una variable y calcular un porcentaje.',
   'QuillayMarket: convertir «mejorar ventas» en una pregunta con período, responsable e indicador.',
   'Cambiar la unidad de venta a cliente y explicar qué agregado deja de ser válido.',
   'Entregar una ficha con pregunta, unidad, fuente, decisión y dos límites.'),
  ('c5','sec-visualizacion','Exploración y comunicación visual','Elegir un resumen y un gráfico coherentes con la pregunta y el denominador.',
   'Ficha del módulo 01; media, mediana y tipo de variable.',
   'Comparar ingresos por producto y evolución mensual sin atribuir causalidad a una línea.',
   'Filtrar un segmento y comprobar si cambia el mensaje al mantener el mismo denominador.',
   'Presentar un gráfico con unidad, período, población y una interpretación verificable.'),
  ('c14','sec-herramientas','Herramientas y caso integrador','Reproducir un indicador con filtros, agregaciones y una unión validada.',
   'Módulos 01–02; claves de una tabla y lectura de una fórmula.',
   'Conciliar el ingreso de QuillayMarket entre pandas y SQL sobre las mismas filas.',
   'Introducir una clave repetida en una copia y detectar por qué se inflan los totales.',
   'Entregar cálculo conciliado, control de cardinalidad y recomendación con sensibilidad.'),
  ('c8','sec-probabilidad','Probabilidad y simulación','Explicar una probabilidad condicionada y la variación de una estimación.',
   'Fracciones, porcentajes y distribuciones descritas en el módulo 02.',
   'Comparar probabilidad de alerta dada una condición y condición dada una alerta.',
   'Cambiar la tasa base conservando sensibilidad y especificidad; anticipar el posterior.',
   'Dibujar una tabla de frecuencias y explicar el efecto de n sin confundir sesgo con precisión.'),
  ('c9','sec-modelos','Puente hacia modelos predictivos','Comparar un modelo con una referencia usando datos reservados.',
   'Módulos 01–02 y noción de probabilidad; ejecutar celdas en orden.',
   'Separar ajuste y evaluación y observar cómo cambia una decisión al mover el umbral.',
   'Justificar un costo distinto de falso negativo y comprobar su efecto en la recomendación.',
   'Informar partición, referencia, métrica, costo y un límite de generalización.') ]},
 'EBA': {'carpeta':'02_Estadistica_Business_Analytics','guia':'guia_maestra_eba.html','nombre':'Estadística Aplicada a Business Analytics',
         'prerrequisito':'Fundamentos: variables, gráficos y porcentajes; lectura y ejecución básica de Python.',
         'modulos':[
  ('sec-problema','sec-problema','Problema, descripción y muestreo','Definir población y estimando y justificar a quién representa la muestra.',
   'Tipos de variables, media, mediana y lectura de gráficos.',
   'ComercioSur: distinguir el marco de 5000 pedidos de la muestra de 600.',
   'Comparar precisión al aumentar n y discutir un marco que excluye un canal.',
   'Entregar contrato de análisis con población, diseño, estimando y fuentes de sesgo.'),
  ('sec-probabilidad','sec-probabilidad','Probabilidad, Bayes y distribuciones','Construir un modelo probabilístico cuyo soporte y supuestos sean explícitos.',
   'Módulo 01; porcentajes y tablas de frecuencias.',
   'En 10000 casos, prevalencia 2%, sensibilidad 90% y especificidad 95% dan 180 alertas verdaderas y 490 falsas.',
   'Modificar la prevalencia y una meta binomial; explicar independencia y tasa base.',
   'Calcular e interpretar el posterior 180/670 y explicar por qué no equivale a sensibilidad.'),
  ('sec-intervalos','sec-intervalos','Estimación e intervalos','Elegir un intervalo según el parámetro, la población y el diseño.',
   'Muestreo y distribuciones de los módulos 01–02.',
   'Contrastar un IC t para tiempo medio con Wilson para proporción de pedidos resueltos.',
   'Cambiar confianza y n; separar variabilidad de pedidos de incertidumbre sobre la media.',
   'Reportar estimación, intervalo, unidad, población objetivo y condiciones de validez.'),
  ('sec-regresion','sec-regresion','Correlación y regresión','Interpretar coeficientes condicionados y evaluar diagnósticos del modelo.',
   'Dispersión, correlación e intervalos; unidad de cada variable.',
   'Modelar tiempo con ticket, canal y campaña y examinar residuos y errores HC3.',
   'Comparar ajuste simple y múltiple y explicar por qué un coeficiente cambia.',
   'Justificar especificación, interpretar un coeficiente y señalar un límite causal.'),
  ('sec-contrastes','sec-contrastes','Contrastes, ANOVA y decisión','Elegir un contraste y comunicar efecto, incertidumbre y relevancia práctica.',
   'Intervalos y diseño independiente o pareado.',
   'Comparar campañas con Welch y ANOVA; usar Holm cuando se examinan varios pares.',
   'Cambiar costo del tratamiento sin modificar p y revisar si cambia la recomendación.',
   'Entregar diferencia, IC, p, ajuste por multiplicidad y una decisión condicionada.'),
  ('sec-series','sec-series','Series y pronóstico','Comparar pronósticos con igual horizonte y orden temporal preservado.',
   'Módulos 01–04; tendencia, estacionalidad y error de predicción.',
   'ComercioSur: 36 meses iniciales, orígenes 36/42/48 y 12 meses finales reservados.',
   'Comparar una referencia estacional con SES, Holt y ARIMA sin seleccionar con prueba.',
   'Dibujar las ventanas y explicar métrica, referencia y dependencia entre errores solapados.'),
  ('sec-visualizacion','sec-visualizacion','Visualización y herramientas','Conciliar un indicador entre herramientas y diseñar un tablero interpretable.',
   'Agregaciones, filtros y conclusiones de los módulos anteriores.',
   'Comparar los agregados por canal y campaña en Python y el libro Excel.',
   'Cambiar un filtro, revisar población y denominador y explicar la misma medida en DAX.',
   'Entregar un tablero con unidades, filtros y totales conciliados; identificar qué se ejecutó.'),
  ('sec-comunicacion','sec-comunicacion','Integrador y comunicación','Defender una recomendación con efecto, incertidumbre y costo.',
   'Resultados reproducibles de los módulos 01–07.',
   'ComercioSur: unir comparación de campañas, costo por minuto y supuestos económicos.',
   'Redactar un memo y defenderlo frente a un escenario que invierte la decisión.',
   'Entregar memo, cálculo, gráfico y defensa con población, sensibilidad y siguiente evidencia.') ]},
 'MPN': {'carpeta':'03_Modelos_Predictivos_Negocios','guia':'guia_maestra_mpn.html','nombre':'Modelos Predictivos para los Negocios',
         'prerrequisito':'Python básico, tablas, probabilidad e interpretación de regresión; diagnóstico en NB01.',
         'modulos':[
  ('c1','sec-problema','Problema predictivo','Definir objetivo, horizonte, disponibilidad de variables y referencia.',
   'Leer un DataFrame y distinguir respuesta numérica de categórica.',
   'FinCordillera: predecir abandono con información disponible antes de la decisión.',
   'Clasificar variables por momento de disponibilidad y explicar una fuga de información.',
   'Entregar ficha de problema, referencia y justificación de una técnica; explicar la red mínima.'),
  ('c3','sec-crisp','Preparación sin fuga','Construir un pipeline que aprenda transformaciones solo con entrenamiento.',
   'Módulo 01; nulos, categorías y claves de datos.',
   'Imputar y escalar dentro de la validación en lugar de usar toda la tabla antes de dividir.',
   'Cambiar el mecanismo de valores ausentes y explicar el límite de la imputación.',
   'Demostrar separación de datos, contrato de variables y transformaciones ajustadas sin prueba.'),
  ('c4','sec-regresion','Regresión de demanda','Comparar regresión y alternativas con referencia e incertidumbre de predicción.',
   'Módulos 01–02; coeficientes y errores de regresión.',
   'QuillayMarket: comparar mes numérico con codificación por categoría y revisar residuos.',
   'Modificar un escenario de precio; identificar extrapolación y límites del intervalo.',
   'Reportar MAE/RMSE, referencia, diagnóstico y diferencia entre IC de media e intervalo predictivo.'),
  ('c5','sec-clasificacion','Clasificación de abandono','Evaluar discriminación y una campaña con probabilidades y costos explícitos.',
   'Pipeline, probabilidad y matriz de confusión.',
   'FinCordillera: comparar logística, árbol, KNN escalado y bosque en validación.',
   'Cambiar presupuesto de contactos y comprobar cobertura de casos y costo de campaña.',
   'Justificar modelo y política con métricas fuera de muestra y límites de utilidad.'),
  ('c8','sec-validacion','Validación, métricas y umbral','Seleccionar modelo y umbral sin reutilizar la prueba para decidir.',
   'Módulos 02–04; costos de falsos positivos y negativos.',
   'PulpaLenga: fijar un umbral con predicciones fuera de pliegue y evaluar al final.',
   'Cambiar costos y revisar calibración; distinguir ordenamiento de calidad probabilística.',
   'Documentar selección, datos reservados y costo; no inferir calibración por coincidencia de umbrales.'),
  ('c10','sec-limitaciones','Limitaciones y comunicación','Construir una ficha de modelo con seguimiento, responsables y condiciones de uso.',
   'Métricas, calibración y evaluación por segmentos.',
   'Comparar estabilidad poblacional y desempeño por grupo; no interpretar PSI como causalidad.',
   'Redactar un mensaje ejecutivo y otro técnico para la misma señal de deterioro.',
   'Entregar ficha con evidencia, incertidumbre, umbral de revisión y propuesta de mejora.'),
  ('c16','sec-series','Pronóstico de demanda','Evaluar una serie mediante orígenes móviles y referencias comparables.',
   'Validación temporal, tendencia, estacionalidad y MAE.',
   'QuillayMarket: comparar pronóstico estacional y modelo con variables temporales.',
   'Aumentar el horizonte y analizar cobertura y MASE sin ajustar con los meses de prueba.',
   'Explicar horizonte, cobertura observada, referencia y límites de cambios del proceso.') ]},
 'AED': {'carpeta':'04_Analitica_Estrategica_Datos','guia':'guia_maestra_aed.html','nombre':'Analítica Estratégica de Datos',
         'prerrequisito':'Descriptiva, probabilidad y lectura de modelos; programación lineal se introduce con dos variables.',
         'modulos':[
  ('proceso','sec-proceso','Proceso y calidad','Diseñar un proceso con entregables y reglas de calidad que cambian la decisión.',
   'Claves, tipos de variable y pregunta de negocio.',
   'CasaPeumo: comparar original y derivado; BoldoNet: distinguir cohortes maduras de incompletas.',
   'Mover la fecha de corte y explicar por qué cambia la población elegible del KPI.',
   'Entregar contrato, auditoría, denominadores y registro de exclusiones reproducible.'),
  ('tecnicas','sec-tecnicas','Selección de técnicas','Elegir técnica según pregunta, respuesta, estructura y decisión.',
   'Módulo 01, lectura de regresión, clasificación y segmentación.',
   'Distinguir describir demora, predecir incumplimiento y asignar turnos con capacidad limitada.',
   'Comparar predicción y agrupamiento sobre el mismo caso y discutir cómo se usaría cada salida.',
   'Justificar técnica, referencia, validación y una implicación práctica que no confunda asociación y efecto.'),
  ('kpis','sec-kpis','KPIs y dashboard','Definir y conciliar una medida con grano, unidad, denominador y responsable.',
   'Agregaciones, ratios y calidad del módulo 01.',
   'Ventas de 100 y 900 con márgenes 50 y 90: margen total 140/1000 = 14%, no 30%.',
   'Filtrar canal y región y conciliar pandas, SQL y la definición DAX.',
   'Entregar ficha de KPI y tablero con fuente, población, período y acción ante desviaciones.'),
  ('restricciones','sec-optimizacion','Optimización y restricciones','Formular y resolver una decisión factible e interpretar sensibilidad local.',
   'Ecuaciones lineales, unidades y costos de oportunidad.',
   'Con 100 horas y 90 de material, A=110/3 y B=80/3 producen 6800/3 UM.',
   'Cambiar horas a 110 y después a 200; comprobar cuándo deja de valer el precio sombra inicial.',
   'Presentar variables, objetivo, restricciones, solución, holguras y una decisión de capacidad.'),
  ('decision','sec-decision','Alternativas e información','Comparar acciones bajo riesgo y valorar información antes de pagar por ella.',
   'Probabilidades y valor esperado; distinguir acción de estado del mundo.',
   'Con p alto = 0,4: expandir vale 20 kUM y piloto 27; información perfecta vale como máximo 14.',
   'Mover p a 0,6 y contrastar valor esperado, peor caso y preferencia del decisor.',
   'Entregar matriz de pagos, alternativa, sensibilidad y cota del costo de información.'),
  ('simulacion','sec-simulacion','SolarSur y Monte Carlo','Comparar proyectos con flujos, dependencia y precisión numérica explícitos.',
   'Valor presente, media, percentiles y distribuciones lognormales.',
   'SolarSur: simular producción y precio dependientes y contrastar VAN medio con su esperanza analítica.',
   'Duplicar escenarios y cambiar correlación por separado; distinguir qué cambio reduce error Monte Carlo.',
   'Informar VAN, pérdida, SE de la media, supuestos y sensibilidad de una recomendación.'),
  ('comunicacion','sec-comunicacion','Integración e implementación','Defender una alternativa y diseñar el piloto que evaluará su efecto.',
   'KPIs, restricciones y análisis de incertidumbre de los módulos anteriores.',
   'Traducir una reducción supuesta de incidentes a beneficio incremental y punto de equilibrio.',
   'Cambiar costo y efecto esperado; formular una métrica primaria y una de protección.',
   'Entregar memo con alternativas, factibilidad, incertidumbre, piloto, responsable y criterio de revisión.'),
  ('avanzado','sec-profundizacion','Profundización prescriptiva','Analizar sensibilidad, colas y aprendizaje secuencial sin extrapolar garantías.',
   'Álgebra, probabilidad, optimización y lectura de funciones en Python.',
   'Comparar media-varianza, riesgo de cola y políticas UCB sobre múltiples semillas.',
   'Modificar aversión al riesgo o mecanismo de recompensa y evaluar estabilidad de la política.',
   'Defender supuestos, criterio de riesgo, comparación independiente y límite de transferencia.') ]},
}

OPCIONALES = {'FBA':{4,5}, 'EBA':set(), 'MPN':{7}, 'AED':{8}}

# Minutos orientativos: explicación, práctica guiada, trabajo autónomo.
TIEMPOS = {
 'FBA': [(30,60,30),(35,85,40),(30,120,60),(30,60,30),(40,110,60)],
 'EBA': [(45,135,45),(30,60,30),(30,60,40),(40,80,45),(40,110,60),(40,110,60),(30,60,45),(20,100,60)],
 'MPN': [(35,85,45),(30,90,45),(45,135,60),(40,110,60),(45,135,75),(35,115,60),(35,85,45)],
 'AED': [(30,90,45),(40,80,45),(30,90,45),(35,85,45),(35,85,45),(40,80,60),(30,90,60),(60,180,90)]
}

def modulos(codigo):
    campos = ('ancla','manual','titulo','objetivo','preparacion','ejemplo','actividad','logro')
    for i, row in enumerate(CURSOS[codigo]['modulos'], 1):
        yield dict(zip(campos,row), numero=i, nivel='Profundización' if i in OPCIONALES[codigo] else 'Núcleo',
                   duracion=f'{sum(TIEMPOS[codigo][i-1][:2])} min guiados + {TIEMPOS[codigo][i-1][2]} min autónomos',
                   explicacion_min=TIEMPOS[codigo][i-1][0], practica_min=TIEMPOS[codigo][i-1][1], autonomo_min=TIEMPOS[codigo][i-1][2])
